In [1]:
# downloading resources and importing libraries
import nltk
nltk.download('punkt')
nltk.download('wordnet')

import pandas as pd
import numpy as np

from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
import re

[nltk_data] Downloading package punkt to C:\Users\pansa.DESKTOP-2QTDA2
[nltk_data]     J\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\pansa.DESKTOP-2QTD
[nltk_data]     A2J\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [2]:
df = pd.read_csv('../internshala_dataset.csv')

In [3]:
# checking the data once
df.isnull().sum()

Title                  0
Company                0
Location               0
Duration               0
Stipend                0
Apply By               0
Applicants             0
Skills Required       68
Perks                  0
Number of Openings     0
Link                   0
dtype: int64

In [4]:
df['Skills Required']

0                                                    NaN
1                                                    NaN
2                             Android , Java , Python ,
3                                       Culinary Arts ,
4      .NET , JavaScript , Node.js , PHP , Python , R...
                             ...
457                                                  NaN
458                                                  NaN
459    English Proficiency (Spoken) , English Profici...
460    English Proficiency (Spoken) , English Profici...
461    English Proficiency (Spoken) , English Profici...
Name: Skills Required, Length: 462, dtype: object

In [5]:
df[df['Skills Required'].isnull()]

,Title,Company,Location,Duration,Stipend,Apply By,Applicants,Skills Required,Perks,Number of Openings,Link
0,Sales & Marketing,Decathlon Sport India Private Limited,Chennai,3 Months,10000 /month,19 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",4,https://internshala.com/internship/detail/sale...
1,Business Development (Sales),Aditya Birla Capital,Kolkata,3 Months,2000-3000 /month,16 Apr' 22,52 applicants,NaN,"Certificate , Letter of recommendation , Job o...",20,https://internshala.com/internship/detail/busi...
11,Digital Marketing,CreativeHigh,Work From Home,3 Months,2000 /month + Incentives,23 Apr' 22,78 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",5,https://internshala.com/internship/detail/digi...
13,Digital Marketing,Weboin,Chennai,6 Months,15000 /month,23 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",13,https://internshala.com/internship/detail/digi...
17,Marketing,Mazatron Enterprise,Noida,6 Months,5000 /month + Incentives,22 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",20,https://internshala.com/internship/detail/mark...
...,...,...,...,...,...,...,...,...,...,...,...
427,Human Resources (HR),Square Select Estates,Hyderabad,6 Months,7000 /month,11 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",1,https://internshala.com/internship/detail/huma...
444,Digital Marketing,Difam (Stallion),Hyderabad,2 Months,3000-8000 /month,10 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",4,https://internshala.com/internship/detail/digi...
453,Personal Assistance,MeetUniversity,Work From Home,6 Months,5000 /month,15 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Job o...",1,https://internshala.com/internship/detail/pers...
457,Human Resources (HR),Graygraph Technologies LLC,Ghaziabad,2 Months,10000 /month,12 Apr' 22,129 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",5,https://internshala.com/internship/detail/huma...
458,Business Development (Sales),Synergies Ananta,Jodhpur,2 Months,4000-9000 /month,15 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",10,https://internshala.com/internship/detail/busi...

In [6]:
df.at[1, 'Skills Required'] = 'Sales and Marketing'

In [7]:
df.loc[df['Title'] == 'Business Development (Sales)', 'Skills Required'] = 'Sales, Marketing'

In [9]:
# checking the data once
df.isnull().sum()

Title                  0
Company                0
Location               0
Duration               0
Stipend                0
Apply By               0
Applicants             0
Skills Required       55
Perks                  0
Number of Openings     0
Link                   0
dtype: int64

In [10]:
df.loc[df['Title'] == 'Human Resources (HR)', 'Skills Required'] = 'Problem Solving, Pulic Relations'

In [11]:
df.loc[df['Title'] == 'Graphic Design', 'Skills Required'] = 'Creativity'

In [12]:
df.loc[df['Title'] == 'Digital Marketing', 'Skills Required'] = 'Digital Marketing'

In [13]:
df.loc[df['Title'] == 'Marketing', 'Skills Required'] = 'Marketing'

In [14]:
# checking the data once
df.isnull().sum()

Title                  0
Company                0
Location               0
Duration               0
Stipend                0
Apply By               0
Applicants             0
Skills Required       33
Perks                  0
Number of Openings     0
Link                   0
dtype: int64

In [15]:
df[df['Skills Required'].isnull()]

,Title,Company,Location,Duration,Stipend,Apply By,Applicants,Skills Required,Perks,Number of Openings,Link
0,Sales & Marketing,Decathlon Sport India Private Limited,Chennai,3 Months,10000 /month,19 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",4,https://internshala.com/internship/detail/sale...
32,Video Making/Editing,Wrig Productions,Pune,2 Months,8000 /month,22 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Infor...",5,https://internshala.com/internship/detail/vide...
33,English Training,Zenith Consultants,Delhi,3 Months,20000 /month,22 Apr' 22,28 applicants,NaN,"Job offer ,",2,https://internshala.com/internship/detail/engl...
47,Electronics Engineering,Griden Power,Ahmedabad,6 Months,5000-8000 /month,22 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",2,https://internshala.com/internship/detail/elec...
58,Social Media Marketing,Weboin,Chennai,3 Months,15000 /month,21 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",18,https://internshala.com/internship/detail/soci...
63,Product Design (Bracelets & Jewelry),ForestFuse,Jaipur,3 Months,3000 /month + Incentives,21 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",2,https://internshala.com/internship/detail/prod...
87,Content Writing,Yink OPC Private Limited,Work From Home,2 Months,3000 /month,20 Apr' 22,186 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",3,https://internshala.com/internship/detail/cont...
117,Content Writing,Strategic Links,Work From Home,3 Months,3000-5000 /month,20 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",2,https://internshala.com/internship/detail/cont...
123,Firmware/Hardware Engineering,Fourth Frontier Technologies Private Limited,Bangalore,2 Months,25000 /month,20 Apr' 22,111 applicants,NaN,"Certificate , Job offer ,",2,https://internshala.com/internship/detail/firm...
132,Dance Facilitation,CreateJoy Technologies Private Limited,Work From Home,6 Months,10000-20000 /month,19 Apr' 22,71 applicants,NaN,"Certificate , Flexible work hours , Job offer ,",30,https://internshala.com/internship/detail/danc...
135,Fundraising (Financial Growth),Badlav Seva Samiti (NGO),Work From Home,1 Month,1000 /month + Incentives,19 Apr' 22,38 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",20,https://internshala.com/internship/detail/fund...
145,Wix Website Development,PassionWorks India,Work From Home,1 Month,Unpaid,19 Apr' 22,58 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",1,https://internshala.com/internship/detail/wix-...
176,Dance Fitness Instruction,Future Lab Studio,Gurgaon,2 Months,9000 /month,18 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",2,https://internshala.com/internship/detail/danc...
191,Research & Development - Chemist,Glocot Silicone Private Limited,Delhi,1 Month,7500-10000 /month,18 Apr' 22,40 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",1,https://internshala.com/internship/detail/rese...
192,Fundraising,Badlav Seva Samiti (NGO),Work From Home,1 Month,1000 /month + Incentives,18 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",20,https://internshala.com/internship/detail/fund...
216,Education Counseling,Sourav Sir's Classes,Kolkata,3 Months,3500-8500 /month,18 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",7,https://internshala.com/internship/detail/educ...
222,Qliksense Development,Exponentia.ai,Mumbai,6 Months,12000 /month,17 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Job o...",3,https://internshala.com/internship/detail/qlik...
226,Subject Matter Expert (Medical),Zealth-AI,Work From Home,6 Months,6000 /month + Incentives,17 Apr' 22,30 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",2,https://internshala.com/internship/detail/subj...
235,Social Media Marketing,Happy60Plus,Delhi,3 Months,6700 /month,17 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",1,https://internshala.com/internship/detail/soci...
239,Property Surveying,Tejarat Marketing,Noida,3 Months,6000 lump sum + Incentives,16 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Job o...",5,https://internshala.com/internship/detail/prop...
252,Operations,Matrix Exports,Bangalore,3 Months,5000-10000 /month,16 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",20,https://internshala.com/internship/detail/oper...
274,Sales & Marketing,Omnis Healthcare Services Private Limited,Work From Home,2 Months,7000 /month,15 Apr' 22,56 applicants,NaN,"Certificate , Flexible work hours , Job offer ,",10,https://internshala.com/internship/detail/sale...
296,Data Entry,Stirring Minds,Delhi,6 Months,3000-6000 /month,15 Apr' 22,209 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",10,https://internshala.com/internship/detail/data...
297,Business Analytics,Stirring Minds,Delhi,2 Months,5000-10000 /month,15 Apr' 22,433 applicants,NaN,"Certificate , Flexible work hours , Job offer ,",3,https://internshala.com/internship/detail/busi...
309,Virtual Assistance,AbroEduShip,Gurgaon,4 Weeks,3000-5000 /month,15 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",5,https://internshala.com/internship/detail/virt...
318,Social Media Marketing,CollegeTips.in,Indore,1 Month,2000-5000 /month,14 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",4,https://internshala.com/internship/detail/soci...
319,Social Media Marketing,CollegeTips.in,Bhopal,1 Month,2000-5000 /month,14 Apr' 22,Be an early applicant,NaN,"Certificate , Flexible work hours , Job offer ,",4,https://internshala.com/internship/detail/soci...
334,Operations,Great Kapital,Bangalore,3 Months,30000 /month,14 Apr' 22,191 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",2,https://internshala.com/internship/detail/oper...
338,Social Media Marketing,Boomingoz Enterprise Private Limited,Work From Home,2 Months,2000-4000 /month,14 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",5,https://internshala.com/internship/detail/soci...
341,Social Media Marketing,Khuraq Healthcare Private Limited,Work From Home,2 Months,5000-8000 /month,14 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",1,https://internshala.com/internship/detail/soci...
360,Web Development,Knowlexon Innovation And Technology Private Li...,Work From Home,3 Months,1000-7000 /month,13 Apr' 22,59 applicants,NaN,"Certificate , Letter of recommendation , Flexi...",3,https://internshala.com/internship/detail/web-...
393,Coaching,Little Kickers India,Bangalore,6 Months,10000 /month + Incentives,11 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Flexi...",2,https://internshala.com/internship/detail/coac...
453,Personal Assistance,MeetUniversity,Work From Home,6 Months,5000 /month,15 Apr' 22,Be an early applicant,NaN,"Certificate , Letter of recommendation , Job o...",1,https://internshala.com/internship/detail/pers...

In [16]:
df.loc[df['Title'] == 'Content Writing', 'Skills Required'] = 'Engish Proficiency'

In [17]:
df.loc[df['Title'] == 'Personal Assistance', 'Skills Required'] = 'Communication Skills'

In [18]:
df.loc[df['Title'] == 'Web Development', 'Skills Required'] = 'Full Stack Development'

In [19]:
df.loc[df['Title'] == 'Social Media Marketing', 'Skills Required'] = 'Social Media Marketing'

In [20]:
df.loc[df['Title'] == 'Virtual Assistance', 'Skills Required'] = 'Communication  Skills'

In [21]:
df.loc[df['Title'] == 'Business Analytics', 'Skills Required'] = 'Data Analysis'

In [22]:
df.loc[df['Title'] == 'Data Entry', 'Skills Required'] = 'Microsoft Excel'

In [23]:
df.loc[df['Title'] == 'Property Surveying', 'Skills Required'] = 'Communication Skills'

In [24]:
df.loc[df['Title'] == 'Subject Matter Expert (Medical)', 'Skills Required'] = 'Medical Expert'

In [25]:
df.loc[df['Title'] == 'Qliksense Development', 'Skills Required'] = 'AI'

In [26]:
df.loc[df['Title'] == 'Education Counseling', 'Skills Required'] = 'Counseling'

In [27]:
# checking the data once
df.isnull().sum()

Title                  0
Company                0
Location               0
Duration               0
Stipend                0
Apply By               0
Applicants             0
Skills Required       16
Perks                  0
Number of Openings     0
Link                   0
dtype: int64

In [28]:
df["Skills Required"].fillna("Communication Skills", inplace = True)

In [29]:
# checking the data once
df.isnull().sum()

Title                 0
Company               0
Location              0
Duration              0
Stipend               0
Apply By              0
Applicants            0
Skills Required       0
Perks                 0
Number of Openings    0
Link                  0
dtype: int64

In [30]:
# checking the shape once again
df.shape

(462, 11)

In [31]:
df['Skills Required'].str.lower()

0                                   communication skills
1                                       sales, marketing
2                             android , java , python ,
3                                       culinary arts ,
4                                 full stack development
                             ...
457                     problem solving, pulic relations
458                                     sales, marketing
459    english proficiency (spoken) , english profici...
460    english proficiency (spoken) , english profici...
461    english proficiency (spoken) , english profici...
Name: Skills Required, Length: 462, dtype: object

In [32]:
df['Location'].str.lower()

0             chennai
1             kolkata
2        kanpur dehat
3               delhi
4              bhopal
            ...
457         ghaziabad
458           jodhpur
459    work from home
460    work from home
461    work from home
Name: Location, Length: 462, dtype: object

In [38]:
df

,id,Title,Company,Location,Duration,Stipend,Apply By,Applicants,Skills Required,Perks,Number of Openings,Link
0,0,Sales & Marketing,Decathlon Sport India Private Limited,Chennai,3 Months,10000 /month,19 Apr' 22,Be an early applicant,Communication Skills,"Certificate , Letter of recommendation , Flexi...",4,https://internshala.com/internship/detail/sale...
1,1,Business Development (Sales),Aditya Birla Capital,Kolkata,3 Months,2000-3000 /month,16 Apr' 22,52 applicants,"Sales, Marketing","Certificate , Letter of recommendation , Job o...",20,https://internshala.com/internship/detail/busi...
2,2,Teaching (Computer Programming),Nimble-Q,Kanpur Dehat,3 Months,1600 /week,24 Apr' 22,Be an early applicant,"Android , Java , Python ,","Certificate , Letter of recommendation , Job o...",1,https://internshala.com/internship/detail/teac...
3,3,Baking - Culinary,Prianka Khushwani,Delhi,6 Months,4000 /month,24 Apr' 22,Be an early applicant,"Culinary Arts ,","Certificate , Letter of recommendation , Flexi...",2,https://internshala.com/internship/detail/baki...
4,4,Web Development,Spring 360 Technology,Bhopal,3 Months,7000-20000 /month,24 Apr' 22,Be an early applicant,Full Stack Development,"Certificate , Letter of recommendation , Flexi...",8,https://internshala.com/internship/detail/web-...
...,...,...,...,...,...,...,...,...,...,...,...,...
457,457,Human Resources (HR),Graygraph Technologies LLC,Ghaziabad,2 Months,10000 /month,12 Apr' 22,129 applicants,"Problem Solving, Pulic Relations","Certificate , Letter of recommendation , Flexi...",5,https://internshala.com/internship/detail/huma...
458,458,Business Development (Sales),Synergies Ananta,Jodhpur,2 Months,4000-9000 /month,15 Apr' 22,Be an early applicant,"Sales, Marketing","Certificate , Letter of recommendation , Flexi...",10,https://internshala.com/internship/detail/busi...
459,459,Campus Management,Ulead,Work From Home,1 Month,2000 /month,15 Apr' 22,1000+ applicants,"English Proficiency (Spoken) , English Profici...","Certificate , Letter of recommendation , Flexi...",10,https://internshala.com/internship/detail/camp...
460,460,Regional Management,Ulead,Work From Home,1 Month,2000 /month,15 Apr' 22,1000+ applicants,"English Proficiency (Spoken) , English Profici...","Certificate , Letter of recommendation , Flexi...",15,https://internshala.com/internship/detail/regi...
461,461,Campus Lead Management,Ulead,Work From Home,1 Month,2000 /month,13 Apr' 22,529 applicants,"English Proficiency (Spoken) , English Profici...","Certificate , Letter of recommendation , Flexi...",15,https://internshala.com/internship/detail/camp...

We have decided to use the following features for creating filters in the app:

1. Skills Required
2. Location
3. Stipend

In the final app, the user will be choosing from the options provided or inputting the data themselves for these categories. Haven't decided on that part yet. Based on the profile ID they have entered, we will be using a content based recommendation system to recommend the user similar profiles. This similarity will be based on the details column.

We will be creating functions to implement the following steps in this notebook : 
1. Normalize : Remove extra signs and numbers form the sentences (everything is already lowercase)
2. Tokenize
3. Remove extra space from all tokens
4. Stem each token

In [33]:
def tokenize(sentences):
    '''
    tokenizes a bunch of sentences after normalizing them and returns stemmed tokens.
    
    INPUT:
    sentences - a paragraph that need to be tokenized
    
    OUTPUT:
    tokens - list of stemmed tokens
    
    '''
    # normalizing, tokenizing, lemmatizing 
    sentences = re.sub('\W',' ',sentences) 
    sentences = re.sub('[0-9]',' ',sentences)

    tokens = word_tokenize(sentences)
    tokens = [i.strip() for i in tokens]
    
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(i) for i in tokens]
    return tokens

In [39]:
def similarity_matrix(df):
    '''
    returns a similarity matrix, in the form of a dataframe, between different internships by using the 
    details section of df.
    
    INPUT:
    df - dataframe with 'details' as one of the columns
    
    OUTPUT:
    sim - similarity matrix(dataframe) with internship id as column and row labels 
    
    '''
    details = df['Skills Required']
    vect = CountVectorizer(tokenizer= tokenize, stop_words = 'english')
    tfidf = TfidfTransformer()
    
    mat = tfidf.fit_transform(vect.fit_transform(details).toarray()).toarray()
    sim = np.dot(mat, mat.T)
    sim = pd.DataFrame(sim, columns=df.id, index = df.id)
    return sim

In [40]:
sim = similarity_matrix(df)

C:\Users\pansa.DESKTOP-2QTDA2J\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'afterward', 'alon', 'alreadi', 'alway', 'ani', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becaus', 'becom', 'befor', 'besid', 'cri', 'describ', 'dure', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'formerli', 'forti', 'ha', 'henc', 'hereaft', 'herebi', 'hi', 'howev', 'hundr', 'inde', 'latterli', 'mani', 'meanwhil', 'moreov', 'mostli', 'nobodi', 'noon', 'noth', 'nowher', 'onc', 'onli', 'otherwis', 'ourselv', 'perhap', 'pleas', 'seriou', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'themselv', 'thenc', 'thereaft', 'therebi', 'therefor', 'thi', 'thu', 'togeth', 'twelv', 'twenti', 'veri', 'wa', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev', 'whi', 'yourselv'] not in stop_words.
  warnings.warn(

In [41]:
sim.shape

(462, 462)

In [42]:
sim.to_csv('../data_for_notebooks/internshala_recommendation_matrix.csv', index = True)

# ***

After trying out the recommendations in the make_recs notebook, I have come back to this notebook to make some changes. I think that we can maybe make better recommendations and thus we will try a few things out with this data(since it isn't big at all).

The few ways that I can think of right now to change how recommendations are made:
1. Do not use Tfidf and but stem tokens
2. Lemmatize the words instead of stemming them
3. Use lemmatization and do not use tfidf

1. Do not use Tfidf

In [44]:
def similarity_matrix_wo_tfidf(df):
    '''
    returns a similarity matrix, in the form of a dataframe, between different internships by using the 
    details section
    
    INPUT:
    df - dataframe with 'skills required' as one of the columns
    
    OUTPUT:
    sim - similarity matrix(dataframe) with internship id as column and row labels 
    
    '''
    details = df['Skills Required']
    vect = CountVectorizer(tokenizer= tokenize, stop_words = 'english')
    
    mat = vect.fit_transform(details).toarray()
    sim = np.dot(mat, mat.T)
    sim = pd.DataFrame(sim, columns=df.id, index = df.id)
    return sim

In [45]:
sim_1 = similarity_matrix_wo_tfidf(df)
sim_1.to_csv('../data_for_notebooks/internshala_recommendation_matrix_wo_tfidf.csv', index = True)

C:\Users\pansa.DESKTOP-2QTDA2J\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'afterward', 'alon', 'alreadi', 'alway', 'ani', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becaus', 'becom', 'befor', 'besid', 'cri', 'describ', 'dure', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'formerli', 'forti', 'ha', 'henc', 'hereaft', 'herebi', 'hi', 'howev', 'hundr', 'inde', 'latterli', 'mani', 'meanwhil', 'moreov', 'mostli', 'nobodi', 'noon', 'noth', 'nowher', 'onc', 'onli', 'otherwis', 'ourselv', 'perhap', 'pleas', 'seriou', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'themselv', 'thenc', 'thereaft', 'therebi', 'therefor', 'thi', 'thu', 'togeth', 'twelv', 'twenti', 'veri', 'wa', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev', 'whi', 'yourselv'] not in stop_words.
  warnings.warn(

2. Lemmatize the word

In [46]:
def tokenize_lem(sentences):
    '''
    tokenizes a bunch of sentences after normalizing it and returns lemmatized tokens.
    
    INPUT:
    sentences - a paragraph that needs to be tokenized
    
    OUTPUT:
    tokens - list of lemmatized tokens
    
    '''
    # normalizing, tokenizing, lemmatizing 
    sentences = re.sub('\W',' ',sentences) 
    sentences = re.sub('[0-9]',' ',sentences)

    tokens = word_tokenize(sentences)
    tokens = [i.strip() for i in tokens]
    
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(i) for i in tokens]
    return tokens

In [48]:
def similarity_matrix_w_lem(df):
    '''
    returns a similarity matrix, in the form of a dataframe, between different internships by using the 
    details section
    
    INPUT:
    df - dataframe with 'Skills Required' as one of the columns
    
    OUTPUT:
    sim - similarity matrix(dataframe) with internship id as column and row labels 
    
    '''
    details = df['Skills Required']
    vect = CountVectorizer(tokenizer= tokenize_lem, stop_words = 'english')
    tfidf = TfidfTransformer()
    
    mat = tfidf.fit_transform(vect.fit_transform(details).toarray()).toarray()
    sim = np.dot(mat, mat.T)
    sim = pd.DataFrame(sim, columns=df.id, index = df.id)
    return sim

In [50]:
import nltk
nltk.download('omw-1.4')
sim_2 = similarity_matrix_w_lem(df)
sim_2.to_csv('../data_for_notebooks/internshala_recommendation_matrix_w_lem.csv', index = True)

[nltk_data] Downloading package omw-1.4 to C:\Users\pansa.DESKTOP-2QTD
[nltk_data]     A2J\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\omw-1.4.zip.
C:\Users\pansa.DESKTOP-2QTDA2J\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  warnings.warn(

3. Use lemmatization and do not use tfidf

In [52]:
def similarity_matrix_w_lem_wo_tfidf(df):
    '''
    returns a similarity matrix, in the form of a dataframe, between different internships by using the 
    details section
    
    INPUT:
    df - dataframe with 'Skills Required' as one of the columns
    
    OUTPUT:
    sim - similarity matrix(dataframe) with internship id as column and row labels 
    '''
    details = df['Skills Required']
    vect = CountVectorizer(tokenizer= tokenize_lem, stop_words = 'english')
    tfidf = TfidfTransformer()
    
    mat = vect.fit_transform(details).toarray()
    sim = np.dot(mat, mat.T)
    sim = pd.DataFrame(sim, columns=df.id, index = df.id)
    return sim

In [53]:
sim_3 = similarity_matrix_w_lem_wo_tfidf(df)
sim_3.to_csv('../data_for_notebooks/internshala_recommendation_matrix_w_lem_wo_tfidf.csv', index = True)

C:\Users\pansa.DESKTOP-2QTDA2J\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  warnings.warn(

After forming these 3 with the details section, we try an alternate approach and try to use the 'category' column to form the similarity matrix. This should give us more relevant results as there are a high no. of common categories and similar internships have really similar category names. Thus, in the make_recs notebook, we will try using this too and compare it with the results of the above 3.

In [54]:
def similarity_matrix_cat(df):
    '''
    returns a similarity matrix, in the form of a dataframe, between different internships by using the 
    cat section
    
    INPUT:
    df - dataframe with 'Title' as one of the columns
    
    OUTPUT:
    sim - similarity matrix(dataframe) with internship id as column and row labels 
    '''
    cats = df['Title']
    vect = CountVectorizer(tokenizer= tokenize, stop_words = 'english')
    tfidf = TfidfTransformer()
    
    mat = vect.fit_transform(cats).toarray()
    sim = np.dot(mat, mat.T)
    sim = pd.DataFrame(sim, columns=df.id, index = df.id)
    return sim

*Note: The above has been formed in a similar way to sim_1, i.e, without tfidf and with stemming the tokens.This is because when we actually compare the recommendations given using different similarity matrices, we see that sim_1 gives us the best results. Thus later, what we do is that we combine both of sim_1 and sim_cat to get relevant and interesting recommendations. If sim_cat had been made using tdidf then the value of its elements would have been really small compared to sim_1's and it would have been a little difficult trying to make a similarity matrix which uses both of these to make recommendations.*

In [55]:
sim_cat = similarity_matrix_cat(df)

C:\Users\pansa.DESKTOP-2QTDA2J\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'afterward', 'alon', 'alreadi', 'alway', 'ani', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becaus', 'becom', 'befor', 'besid', 'cri', 'describ', 'dure', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'formerli', 'forti', 'ha', 'henc', 'hereaft', 'herebi', 'hi', 'howev', 'hundr', 'inde', 'latterli', 'mani', 'meanwhil', 'moreov', 'mostli', 'nobodi', 'noon', 'noth', 'nowher', 'onc', 'onli', 'otherwis', 'ourselv', 'perhap', 'pleas', 'seriou', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'themselv', 'thenc', 'thereaft', 'therebi', 'therefor', 'thi', 'thu', 'togeth', 'twelv', 'twenti', 'veri', 'wa', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev', 'whi', 'yourselv'] not in stop_words.
  warnings.warn(

In [56]:
sim_cat.to_csv('../data_for_notebooks/internshala_recommendation_df_cat.csv', index = True)